routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


// Route::get('/home', 'HomeController@index')->name('home');
Route::get('/user', 'HomeController@user')->name('user');
Route::get('/admin', 'HomeController@admin')->name('admin');

Route::resource('course','CourseController');
Route::resource('catgoerys','categoery');
Route::resource('subcategoerys','subcategoerys');

Auth::routes();

app/catgoery.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class catgoery extends Model
{


}

resources/views/Catgoery/catgoery.blade.php
@extends('layouts.appbackend')

@section('content')
<div class="container-fluid">
@if ($message = Session::get('success'))
        <div class="alert alert-success alert-block">
            <button type="button" class="close" data-dismiss="alert">×</button>
                <strong>{{ $message }}</strong>
        </div>
        <img src="uploads/{{ Session::get('file') }}">
        @endif
  
        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

    <a  class="btn btn-info text-white my-3" href="{{route('catgoerys.create')}}">Add new catgoerys</a>
<table class="table table-striped">
<thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">name</th>
      <th scope="col">img</th>
      <th scope="col">describtion</th>

    </tr>
  </thead>
  <tbody>
      @foreach($catgoery as $cate)
      <tr>
    
      <th scope="row">{{$cate->id}}</th> 
      <th scope="row">{{$cate->nameCatgorey}}</th> 

      <th scope="row"><img src="{{url('uploads/catge/',$cate->img)}}" > </th> 
      <th scope="row">{{$cate->nameCatgorey}}</th> 
    </tr>
      @endforeach
      
</tbody>
</table>
</div>
@endsection

resources/views/Catgoery/create.blade.php
@extends('layouts.appbackend')

@section('content')
<div class="container">
<h1 class="text-center"> Create Categoery</h1>
<form method="post" action="{{route('catgoerys.store')}}" enctype="multipart/form-data">
            @csrf
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">name</label>
    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="nameCatgorey">
  </div>

  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Image</label>
    <input type="file" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="img">
  </div>

  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Start Time</label>
    <input type="datetime-local" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="start">
  </div>

  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">End Time</label>
    <input type="datetime-local" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="end">
  </div>


  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">describtion</label>
    <textarea id="w3review" class="form-control" name="dsceribtion" rows="4" cols="50">

</textarea>  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

</table>
</div>
@endsection