routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


// Route::get('/home', 'HomeController@index')->name('home');
Route::get('/user', 'HomeController@user')->name('user');
Route::get('/admin', 'HomeController@admin')->name('admin');

Route::resource('course','CourseController');
Route::resource('catgoerys','categoery');
Route::resource('subcategoerys','subcategoerys');

Auth::routes();

app/subCategoery.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class subCategoery extends Model
{
    //
}

app/Http/Controllers/subcategoerys.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\subCategoery;
use App\catgoery;

class subcategoerys extends Controller
{
    /**
     * Display a listing of the resource.
     *subCategoery
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $subcategoery=subcategoery::all();
        return view('SubCategoery.subCategoery',compact('subcategoery'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $catgoery=catgoery::all();
        return view('SubCategoery.create',compact('catgoery'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $catgoery=new subCategoery();
        $catgoery->name=$request->name;
        $imgname = time().'.'.$request->img->extension();
        $request->img->move(public_path('uploads/subCateg'), $imgname);
        $catgoery->imges=$imgname;
        $catgoery->numberCategoery_id=$request->catgeory;

        $catgoery->save();

        return back()
            ->with('success','You have successfully upload file.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/SubCategoery/create.blade.php
@extends('layouts.appbackend')

@section('content')
<div class="container">
<h1 class="text-center"> Create Categoery</h1>
<form method="post" action="{{route('subcategoerys.store')}}"enctype="multipart/form-data" >
            @csrf
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">name</label>
    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="name">
  </div>

  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">img</label>
    <input type="file" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="img">
  </div>

  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">categoery</label>
    <select name="catgeory" class="form-control">
     @foreach($catgoery as $cat)
     <option value={{$cat->id}}>{{$cat->nameCatgorey}}</option>
     @endforeach

</select>
  </div>


  <button type="submit" class="btn btn-primary">Submit</button>
</form>

</table>
</div>
@endsection

resources/views/SubCategoery/subCategoery.blade.php
@extends('layouts.appbackend')

@section('content')
<div class="container-fluid">
@if ($message = Session::get('success'))
        <div class="alert alert-success alert-block">
            <button type="button" class="close" data-dismiss="alert">×</button>
                <strong>{{ $message }}</strong>
        </div>
        <img src="uploads/{{ Session::get('file') }}">
        @endif
  
        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

    <a  class="btn btn-info text-white my-3" href="{{route('subcategoerys.create')}}">Add new sub Categoery</a>
<table class="table table-striped">
<thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">name</th>
      <th scope="col">img</th>


    </tr>
  </thead>
  <tbody>
      @foreach($subcategoery as $as)
      <tr>
    
      <th scope="row">{{$as->id}}</th> 
      <th scope="row">{{$as->name}}</th> 
      <td><img src="{{url('uploads/subCateg',$as->imges)}}"   class="img-thumbnail" width="100"> </td>

      </tr>

      @endforeach
      
</tbody>
</table>
</div>
@endsection