routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


// Route::get('/home', 'HomeController@index')->name('home');
Route::get('/user', 'HomeController@user')->name('user');
Route::get('/admin', 'HomeController@admin')->name('admin');

Route::resource('course','CourseController');
Route::resource('catgoerys','categoery');
Route::resource('subcategoerys','subcategoerys');

Auth::routes();

app/Follow.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Follow extends Model
{
    //
}

app/Models/Permission.php
<?php

namespace App\Models;

use Laratrust\Models\LaratrustPermission;

class Permission extends LaratrustPermission
{
    public $guarded = [];
}

app/Models/Role.php
<?php

namespace App\Models;

use Laratrust\Models\LaratrustRole;

class Role extends LaratrustRole
{
    public $guarded = [];
}

app/Rate.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Rate extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Passport\HasApiTokens;
use Laratrust\Traits\LaratrustUserTrait;

class User extends Authenticatable
{
    use LaratrustUserTrait;
    use HasApiTokens,Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class article extends Model
{
    //
}

app/catgoery.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class catgoery extends Model
{


}

app/chat.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class chat extends Model
{
    //
}

app/comments.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class comments extends Model
{
    //
}

app/couses.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class couses extends Model
{
    //
}

app/fave.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class fave extends Model
{
    //
}

app/getvideo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class getvideo extends Model
{
    //
}

app/history.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class history extends Model
{
    //
}

app/history_product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class history_product extends Model
{
    //
}

app/like.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class like extends Model
{
    //
}

app/subCategoery.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class subCategoery extends Model
{
    //
}

app/videos.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class videos extends Model
{
    //
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/apicategoery.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\catgoery;

class apicategoery extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $catgoery=catgoery::all()->take(4);
        return response()->json(['catgoery'=>$catgoery,'message'=>'success'],200);
    }
    public function all()
    {
        $catgoery=catgoery::paginate(9);
        return response(['catgoery'=>$catgoery,'message'=>'success'],200);
    }
    public function orders($order)
    {
        if($order=="old"){
        $catgoery=catgoery::where('Status',1)->orderBy('id','DESC')->paginate(9);
        }else{
            $catgoery=catgoery::where('Status',1)->orderBy('id','ASC')->paginate(9);

        }
        return response(['catgoery'=>$catgoery,'message'=>'success'],200);
    }

    public function sreach($sreach)
    {
        $catgoery=catgoery::where('nameCatgorey', 'LIKE', "%{$sreach}%")->get();
        return response()->json(['catgoery'=>$catgoery,'message'=>'success'],200);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
         $catgoery=catgoery::find($id);
    return response()->json(['catgoery'=>$catgoery,'message'=>'success'],200);

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/categoery.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\catgoery;
use Session;

class categoery extends Controller
{
  
    public function __construct()
    {
        $this->middleware('auth');
    }  /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $catgoery=catgoery::all();
        return view('Catgoery.catgoery',compact('catgoery'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Catgoery.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $catgoery=new catgoery();
        $catgoery->nameCatgorey=$request->nameCatgorey;
        $catgoery->start=$request->start;
        $catgoery->end=$request->end;
        $catgoery->dsceribtion=$request->dsceribtion;
        
        $imgname = time().'.'.$request->img->extension();  
        $request->img->move(public_path('uploads/catge'), $imgname);
        $catgoery->img=$imgname;

        $catgoery->save();
        return redirect()->back()->with('success', 'Success');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin.blade.php
admin

resources/views/courses/courses.blade.php
@extends('layouts.appbackend')

@section('content')
<div class="container-fluid">
@if ($message = Session::get('success'))
        <div class="alert alert-success alert-block">
            <button type="button" class="close" data-dismiss="alert">×</button>
                <strong>{{ $message }}</strong>
        </div>
        <img src="uploads/{{ Session::get('file') }}">
        @endif
  
        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

    <a  class="btn btn-info text-white my-3" href="{{route('course.create')}}">Add new Courses</a>
<table class="table table-striped">
<thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">name</th>
      <th scope="col">image</th>
      <th scope="col">numberOfVideo</th>
      <th scope="col">created_T</th>

    </tr>
  </thead>
  <tbody>
      @foreach($couses as $as)
      <tr>
    
      <th scope="row">{{$as->id}}</th> 
      <th scope="row">{{$as->name}}</th> 

      <td><img src="{{url('uploads',$as->imges)}}"   class="img-thumbnail" width="100"> </td>
      <td>{{$as->numberOfVideo}}</td>
      <td>{{$as->created_at}}</td>
      </tr>

      @endforeach
      
</tbody>
</table>
</div>
@endsection

resources/views/courses/create.blade.php
@extends('layouts.appbackend')

@section('content')
<div class="container">

<form method="post" action="{{route('course.store')}}" enctype="multipart/form-data">
            @csrf
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">name</label>
    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="name">
  </div>

  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">img</label>
    <input type="file" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="img">
  </div>

<!-- 
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">video</label>
    <input type="file" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="video[]">

  </div> -->

  <div class="input-group hdtuto control-group lst increment" >
      <input type="file" name="video[]" class="myfrm form-control">
      <div class="input-group-btn"> 
        <button class="btn btn-success" type="button"><i class="fldemo glyphicon glyphicon-plus"></i>Add</button>
      </div>
    </div>
    <div class="clone hide">
      <div class="hdtuto control-group lst input-group" style="margin-top:10px">
        <input type="file" name="video[]" class="myfrm form-control"multiple >
        <div class="input-group-btn"> 
          <button class="btn btn-danger" type="button"><i class="fldemo glyphicon glyphicon-remove"></i> Remove</button>
        </div>
      </div>
    </div>


  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">categoery</label>
    <select name="catgeory" class="form-control">
     @foreach($catgoery as $cat)
     <option value={{$cat->id}}>{{$cat->name}}</option>
     @endforeach

</select>
  </div>

  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">number of video</label>
    <input type="number" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="numvideo">
    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
  </div>


  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">describtion</label>
    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"name="desc">
  </div>

  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">age</label>
    <input type="number" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="age">
  </div>

  <button type="submit" class="btn btn-primary">Submit</button>
</form>

</table>
</div>




<script type="text/javascript">
    $(document).ready(function() {
      $(".btn-success").click(function(){ 
          var lsthmtl = $(".clone").html();
          $(".increment").after(lsthmtl);
      });
      $("body").on("click",".btn-danger",function(){ 
          $(this).parents(".hdtuto control-group lst").remove();
      });
    });
</script>
@endsection

resources/views/home.blade.php
@extends('layouts.appbackend')
@section('content')


        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->


<h1 >Information</h1>

<div class="cardGroup" id="demo">

  <div class="card cardGroup__card">
    <div class="card__description cardGroup__cardDescription hvr"
         id="color-1">Number Of Course:{{$catgoery}}
    </div>

  </div>

  <div class="card cardGroup__card">
    <div class="card__description cardGroup__cardDescription hvr"
         id="color-2">Number Of sub Course :{{$subcategoery}}
    </div>
  </div>

  <div class="card cardGroup__card hvr-rectangle-in">
    <div class="card__description cardGroup__cardDescription hvr"
         id="color-3">partions:{{$couses}}
    </div>
  </div>

  <py-script>
      print('this is pathon')
  </py-script>
<!--
  <div class="card cardGroup__card hvr-rectangle-in">
    <div class="card__description cardGroup__cardDescription hvr"
         id="color-4">Alternative 2
    </div>
  </div> -->


        </div>
       @endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>SignUp and Login</title>
	<link rel="stylesheet" type="text/css" href="style.css">
</head>


<body>
<div class="container" id="container">

            @yield('content')
            <div class="overlay-container">
	<div class="overlay">
		<div class="overlay-panel overlay-left">
			<h2>Welcome Back!</h2>
			<p>Sign in now and enjoy our feature and Services </p>
			<button class="ghost" id="signIn">Sign In</button>
		</div>
		<div class="overlay-panel overlay-right">
			<h2>Welcome</h2>
			<p>Dont have an Account!?,sign up now </p>
			<button class="ghost" id="signUp">Sign Up</button>
		</div>
	</div>
</div>
</div>
<script type="text/javascript">
	const signUpButton = document.getElementById('signUp');
	const signInButton = document.getElementById('signIn');
	const container = document.getElementById('container');

	signUpButton.addEventListener('click', () => {
		container.classList.add("right-panel-active");
	});
	signInButton.addEventListener('click', () => {
		container.classList.remove("right-panel-active");
	});
</script>


</body>
</html>

resources/views/layouts/appbackend.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css" />

        <script>
        jQuery(document).ready(function($){
            $("#menu-toggle").click(function(e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
            });
        })
        </script>
        <style>
            body {
        overflow-x: hidden;
        }

        #sidebar-wrapper {
        min-height: 100vh;
        margin-left: -15rem;
        -webkit-transition: margin .25s ease-out;
        -moz-transition: margin .25s ease-out;
        -o-transition: margin .25s ease-out;
        transition: margin .25s ease-out;
        }

        #sidebar-wrapper .sidebar-heading {
        padding: 0.875rem 1.25rem;
        font-size: 1.2rem;
        }

        #sidebar-wrapper .list-group {
        width: 15rem;
        }

        #page-content-wrapper {
        min-width: 100vw;
        }

        #wrapper.toggled #sidebar-wrapper {
        margin-left: 0;
        }

        @media (min-width: 768px) {
        #sidebar-wrapper {
            margin-left: 0;
        }

        #page-content-wrapper {
            min-width: 0;
            width: 100%;
        }

        #wrapper.toggled #sidebar-wrapper {
            margin-left: -15rem;
        }
        }
        /*=====================================================
  Card Colors
  =====================================================*/

#color-1 {
    background: #ffea00;
    color: #000000;
}
#color-2 {
    background: orange;
    color: #000000;
}
#color-3 {
    background: #ff0047;
    color: #000000;
}
#color-4 {
    background: #6A2C70;
    color: #DC59E8;
}

/*=====================================================
  Card Group
  =====================================================*/
  
/* Hover Effect */
.hvr {
  display: inline-block;
  vertical-align: middle;
  -webkit-transform: translateZ(0);
  transform: translateZ(0);
  box-shadow: 0 0 1px rgba(0, 0, 0, 0);
  -webkit-backface-visibility: hidden;
  backface-visibility: hidden;
  -moz-osx-font-smoothing: grayscale;
  position: relative;
  overflow: hidden;
}
.hvr:before {
  content: "";
  position: absolute;
  z-index: -1;
  left: 50%;
  right: 50%;
  top: 0;
  background: #ffff;
  height: 4px;
  -webkit-transition-property: left, right;
  transition-property: left, right;
  -webkit-transition-duration: 0.3s;
  transition-duration: 0.3s;
  -webkit-transition-timing-function: ease-out;
  transition-timing-function: ease-out;
}
.hvr:hover:before, .hvr-overline-from-center:focus:before, .hvr-overline-from-center:active:before {
  left: 0;
  right: 0;
}
#color-1.hvr:before {
  background: #000;
}
#color-2.hvr:before {
  background: #BE3A00;
}
#color-3.hvr:before {
  background: #FD81A4;
}
#color-4.hvr:before {
  background: #DC59E8;
}
/*   
  
.card {
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
  
  -webkit-flex-direction: column;
      -ms-flex-direction: column;
          flex-direction: column;
          
  border: 0px solid #E0E0E0;
  border-radius: 4px;
  overflow: hidden;
} */

.card__description {
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;

  -webkit-flex-direction: column;
      -ms-flex-direction: column;
          flex-direction: column;
          
  -webkit-align-items: center;
       -ms-flex-align: center;
          align-items: center;

  -webkit-justify-content: center;
            -ms-flex-pack: center;
          justify-content: center;

  padding: 15px 0;
  height: 120px;
}


.card__color {
  text-align: center;
  color: #57727C;
  font-size: 15px;
  letter-spacing: 1px;
  padding: 5px 15px;
  background-color: #FEFEFE;
}

.card__color span {
    display: block;
    padding: 5px 0;
}

.card--fixedWidth {
  max-width: 120px;
}


.cardGroup {
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;

  border-radius: 4px;
  overflow: hidden;
}

.cardGroup__card {
  -webkit-flex: 1 1 0%;
      -ms-flex: 1 1 0%;
          flex: 1 1 0%;

  border: none;
  border-radius: 0;
}

.cardGroup__card + .cardGroup__card {
}

.cardGroup__cardDescription {
  -webkit-flex: 1 1 auto;
      -ms-flex: 1 1 auto;
      height: 227px;
    margin: 29px;
          flex: 1 1 auto;
}

/*=====================================================
  Demo
  ==============================    =======================*/
.container {
    padding: 50px;

    overflow-x: auto;
}

#demo {
    margin: 100px;
}

h1 {
    font-size: 40px;
    font-weight: 700;
    color: #000;
    text-align: center;
}

p {
    text-align: center;
}

        </style>    
    </head>
    <body>
    
    <div class="d-flex" id="wrapper">


    @include('par.sidebar')
    <div id="page-content-wrapper">

    @include('par.nav')

    @if (Session::has('success'))
    <div class="alert alert-success">
        <ul>
            <li>{{ Session::get('success') }}</li>
        </ul>
    </div>
@endif      
            @yield('content')
            </div>
        </div>

  </body>
</html>

resources/views/par/nav.blade.php
        <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
            <button class="btn btn-primary" id="menu-toggle">Toggle Menu</button>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>                </li>
                <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Dropdown
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
                </li>
            </ul>
            </div>
        </nav>

resources/views/par/sidebar.blade.php
<div class="bg-light border-right" id="sidebar-wrapper">  

<div class="sidebar-heading">Myadmin </div>
        <div class="list-group list-group-flush">
            <a href="{{route('course.index')}}" class="list-group-item list-group-item-action bg-light">course</a>
            <a href="{{route('catgoerys.index')}}" class="list-group-item list-group-item-action bg-light">catgoerys</a>
            <a href="{{route('subcategoerys.index')}}" class="list-group-item list-group-item-action bg-light">Sub Categoerys</a>
            
        </div>
        </div>

resources/views/user.blade.php
sadsadsasd